server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: snc-gw-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  webflux:
    base-path: /api/v1

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: snc-gw-service
      auto-offset-reset: earliest
      topic: snc-gw-service
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      snc-consumer-topic: snc-gw-service
      snc-producer-topic: snc-gw-service
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  server:
    port: 8081
    base-path: /